#!/bin/bash
#
# Set up initramfs to unlock all LUKS containers described by the PMAP

set -eu

case "${IGconf_image_pmap-}" in
   crypt*) : ;;
   *) exit 0 ;;
esac

pkgs=(cryptsetup-bin initramfs-tools kpartx libgcc-s1)
chroot "$1" apt install -y "${pkgs[@]}"

mkdir -p $1/etc/initramfs-tools/hooks
mkdir -p $1/etc/initramfs-tools/scripts/init-premount

# initramfs generation: Create a hook to install tools needed for unlock
# and block device probe
cat <<- 'EOF' > $1/etc/initramfs-tools/hooks/rpi-cryptroot-install
#!/bin/sh
case $1 in
   prereqs) echo ""; exit 0;;
esac
. /usr/share/initramfs-tools/hook-functions
copy_exec /usr/sbin/kpartx
copy_exec /usr/sbin/cryptsetup

# https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1958594
for so in $(ldconfig -p | sed -nr 's/^\s*libgcc_s\.so.*=>\s*//p'); do
   copy_exec "$so"
done

for module in $(find /usr/lib/modules/$version \
   \( \
   -name 'dm-mod.*' \
   -o \
   -name 'dm-crypt.*' \
   -o \
   -name 'af_alg.*' \
   -o \
   -name 'algif_skcipher.*' \
   -o \
   -name 'libaes.*' \
   -o \
   -name 'aes_generic.*' \
   -o \
   -name 'aes-arm64.*' \
   -o \
   -name 'libpoly1305.*' \
   -o \
   -name 'nhpoly1305.*' \
   -o \
   -name 'adiantum.*' \
   -o \
   -name 'libchacha.*' \
   -o \
   -name 'chacha-neon.*' \
   -o \
   -name 'chacha_generic.*' \
   \) \
   -exec basename {} \; |sed 's/\.ko\.xz$//; s/\.ko$//' ); do
   manual_add_modules $module
done
EOF
chmod +x $1/etc/initramfs-tools/hooks/rpi-cryptroot-install


# Fetch luks containers from the pmap and load into env
pmap --schema "$IGconf_image_pmap_schema" \
     --file "${IGconf_image_outputdir}/provisionmap.json" \
     --cryptvars > "${IGconf_image_outputdir}/crypt.containers"

source "${IGconf_image_outputdir}/crypt.containers"


# initramfs run-time: Create a script to unlock all containers
cat > $1/etc/initramfs-tools/scripts/init-premount/rpi-cryptroot <<'EOF'
#!/bin/sh
export "PATH=/usr/sbin:/usr/bin:$PATH"
case \$1 in
   prereqs) echo ""; exit 0;;
esac
. /scripts/functions

msg() {
   if [ -w /dev/kmsg ]; then
      echo "$@" > /dev/kmsg 2>/dev/null || :
   fi
   echo "$@"
}

EOF

# Emit one block per container
for container in "${CONTAINERS[@]}"; do
   uuid_var="${container}_UUID"
   name_var="${container}_MNAME"
   uuid="${!uuid_var}"
   name="${!name_var}"

   cat >> $1/etc/initramfs-tools/scripts/init-premount/rpi-cryptroot <<EOF
msg "Unlock $uuid ($name)"
echo -n foobar | cryptsetup luksOpen /dev/disk/by-uuid/$uuid $name
if [ $? -ne 0 ]; then
    msg "Failed to unlock $uuid" >&2
    reboot -f # system will be unusable as intended
fi
kpartx -a /dev/mapper/$name
EOF
done
chmod +x $1/etc/initramfs-tools/scripts/init-premount/rpi-cryptroot
