#!/bin/sh

PREREQ=""
prereqs()
{
   echo "$PREREQ"
}

case $1 in
   prereqs)
      prereqs
      exit 0
      ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/kpartx || true
copy_exec /usr/sbin/cryptsetup
copy_exec /usr/bin/rpi-fw-crypto
copy_exec /usr/bin/block-device-id

# https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1958594
for so in $(ldconfig -p | sed -nr 's/^\s*libgcc_s\.so.*=>\s*//p'); do
   copy_exec "$so"
done

# Install cipher-derived modules for this kernel version.
conf="/etc/initramfs-tools/conf.d/rpi-cryptroot-modules-${version}"
if [ -r "$conf" ]; then
   for m in $(cat "$conf"); do
      manual_add_modules "$m"
   done
fi
