#!/bin/sh
#
# Start the network....
#

mkdir -p /run/network

case "$1" in
  start)
  printf "Starting network: "
  /usr/bin/ifup -a
  [ $? = 0 ] && echo "OK" || echo "FAIL"
  ;;
  stop)
  printf "Stopping network: "
  /usr/bin/ifdown -a
  [ $? = 0 ] && echo "OK" || echo "FAIL"
  ;;
  restart|reload)
  "$0" stop
  "$0" start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
